defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.11.3

restore_cache: &restore_cache
  restore_cache:
    keys:
      - v1-dependencies-{{ checksum "package.json" }}
      - v1-dependencies-

save_cache: &save_cache
  save_cache:
    paths:
      - node_modules
    key: v1-dependencies-{{ checksum "package.json" }}

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run: npm install
      - run: npm run lint
      - run: npm test
      - run: ~/repo/node_modules/.bin/codecov -t $CODECOV_TOKEN
      - *save_cache

  publish:
    <<: *defaults
    steps:
      -checkout
      - *restore_cache
      - run:
          name: NPM Access ($NPM_WRITE_TOKEN set in Circle)
          command: echo "//registry.npmjs.org/:_authToken=$NPM_WRITE_TOKEN" >> ~/repo/.npmrc
      - npm publish

workflows:
  version: 2
  test_all:
    jobs:
      - test
      - publish:
          filters:
            branches:
              only: master
          requires:
            - test
